language: rust

cache:
  cargo: true
  directories:
    - /home/travis/.local/share/cargo-web/emscripten

dist: trusty
sudo: false
addons:
  chrome: stable

rust:
  - nightly
  - stable
  - beta
  - 1.24.1

script:
  - nvm install 9
  - ./ci/install_cargo_web.sh
  - ./ci/run_tests.sh
